name: Swift CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Resolve packages
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project TestTCA.xcodeproj \
            -scheme TestTCA

      - name: Build
        run: |
          set -o pipefail

          xcodebuild \
            -project TestTCA.xcodeproj \
            -scheme TestTCA \
            -destination 'generic/platform=iOS Simulator' \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            clean build

      - name: Enable Swift macros
        run: |
          defaults write com.apple.dt.Xcode \
            IDESkipMacroFingerprintValidation \
            -bool YES
      
          defaults write com.apple.dt.Xcode \
            IDESkipPackagePluginFingerprintValidation \
            -bool YES
      
      - name: Unit Tests
        timeout-minutes: 15
        run: |
          set -o pipefail
      
          xcodebuild \
            -project TestTCA.xcodeproj \
            -scheme TestTCA \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.5' \
            -only-testing:TestTCATests \
            -skip-testing:TestTCAUITests \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            test
