name: Swift CI

on:
  # push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          set -o pipefail

          xcodebuild \
            -project TestTCA.xcodeproj \
            -scheme TestTCA \
            -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.5' \
            -only-testing:TestTCATests \
            -skipMacroValidation \
            CODE_SIGNING_ALLOWED=NO \
            test
